name: "zero123-refine"
tag: "${data.random_camera.height}_${rmspace:${basename:${data.image_path}},_}_refine"
exp_root_dir: "outputs"
seed: 0

data_type: "single-image-datamodule"
data:
  image_path: ./load/images/toothless_rgba.png
  height: [256, 512]  # Start at higher resolution for refinement
  width: [256, 512]
  resolution_milestones: [100]  # Switch resolution earlier
  default_elevation_deg: 5.0
  default_azimuth_deg: 0.0
  default_camera_distance: 3.8
  default_fovy_deg: 20.0
  requires_depth: ${cmaxgt0orcmaxgt0:${system.loss.lambda_depth},${system.loss.lambda_depth_rel}}
  requires_normal: ${cmaxgt0:${system.loss.lambda_normal}}
  random_camera:
    height: [128, 256, 512]
    width: [128, 256, 512]
    batch_size: [8, 4, 2]  # Smaller batch sizes for refinement
    resolution_milestones: [100]
    eval_height: 512
    eval_width: 512
    eval_batch_size: 1
    elevation_range: [-10, 80]
    azimuth_range: [-180, 180]
    camera_distance_range: [3.8, 3.8]
    fovy_range: [20.0, 20.0]
    progressive_until: 0
    camera_perturb: 0.0
    center_perturb: 0.0
    up_perturb: 0.0
    light_position_perturb: 1.0
    light_distance_range: [7.5, 10.0]
    eval_elevation_deg: ${data.default_elevation_deg}
    eval_camera_distance: ${data.default_camera_distance}
    eval_fovy_deg: ${data.default_fovy_deg}
    light_sample_strategy: "dreamfusion"
    batch_uniform_azimuth: False
    n_val_views: 30
    n_test_views: 120

system_type: "zero123-system"
system:
  # Enable refinement mode
  refinement: true
  
  geometry_type: "implicit-volume"
  geometry:
    radius: 2.0
    normal_type: "analytic"
    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    # Finer encoding for refinement
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 20  # Increased for more detail
      base_resolution: 16
      per_level_scale: 1.447269237440378
    mlp_network_config:
      otype: "VanillaMLP"
      activation: "ReLU"
      output_activation: "none"
      n_neurons: 64
      n_hidden_layers: 2

  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 0  # Disable ambient-only for refinement
    textureless_prob: 0.05
    albedo_activation: sigmoid

  background_type: "solid-color-background"

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512
    return_comp_normal: ${cmaxgt0:${system.loss.lambda_normal_smooth}}
    return_normal_perturb: ${cmaxgt0:${system.loss.lambda_3d_normal_smooth}}

  prompt_processor_type: "dummy-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: ""
    prompt: ""

  guidance_type: "stable-zero123-guidance"
  guidance:
    pretrained_config: "./load/zero123/sd-objaverse-finetune-c_concat-256.yaml"
    pretrained_model_name_or_path: "./load/zero123/stable_zero123.ckpt"
    vram_O: ${not:${gt0:${system.freq.guidance_eval}}}
    cond_image_path: ${data.image_path}
    cond_elevation_deg: ${data.default_elevation_deg}
    cond_azimuth_deg: ${data.default_azimuth_deg}
    cond_camera_distance: ${data.default_camera_distance}
    
    # Refinement-specific guidance settings
    guidance_scale: 2.0  # Lower guidance scale for refinement
    min_step_percent: [0, 0.02, 0.05, 500]  # Gradually increase noise
    max_step_percent: [0, 0.7, 0.5, 500]    # Gradually reduce max noise

  freq:
    ref_only_steps: 0
    guidance_eval: 0

  # Refinement-focused loss weights
  loss:
    lambda_sds: 0.05  # Lower SDS weight for refinement
    lambda_rgb: [50, 100., 200., 100]  # Reduced RGB loss
    lambda_mask: 25.   # Reduced mask loss
    lambda_depth: 0.
    lambda_depth_rel: 0.
    lambda_normal: 0.
    lambda_normal_smooth: [50, 3.0, 2.0, 75, 5.0, 100]  # Stronger smoothing
    lambda_3d_normal_smooth: [50, 3.0, 2.0, 75, 5.0, 100]
    lambda_orient: 0.5  # Reduced orientation loss
    lambda_sparsity: 0.1  # Reduced sparsity
    lambda_opaque: 0.1   # Reduced opacity loss
    
    # Refinement-specific losses
    lambda_normal_consistency: 10.0  # Surface consistency
    lambda_laplacian_smoothness: 1.0  # Mesh smoothing

  # Refinement optimizer with lower learning rates
  optimizer:
    name: Adam
    args:
      lr: 0.001  # Much lower learning rate
      betas: [0.9, 0.99]
      eps: 1.e-8

trainer:
  max_steps: 3000  # Shorter refinement training
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 100  # More frequent validation
  enable_progress_bar: true
  precision: 16

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: 500  # Save checkpoints more frequently